#!/bin/bash

function git_current_branch () {
    local ref
    ref=$(command git symbolic-ref --quiet HEAD 2> /dev/null)
    local ret=$?
    if [[ $ret != 0 ]]
    then
	[[ $ret = 128 ]] && return
	ref=$(command git rev-parse --short HEAD 2> /dev/null)  || return
    fi
    echo ${ref#refs/heads/}
}

function update-gh-pages() {
    git checkout gh-pages
    # Need sleep between checkout & merge else the .html files and
    # updated .ipynb files have the same modification timestamp, and
    # make doesn't work. 
    sleep 1
    git merge -m "Merge master" master
    (make -q && echo "Nothing to build.") \
	|| ((make > stdout-make 2> stderr-make \
		    && git commit -a -m "Build.") || \
		(echo 'make failed, stderr:' && cat stderr-make))
    git checkout master
}

if [ "$(git_current_branch)" = "master" ] ; then
    update-gh-pages
fi
